title: Tao LEI 雷涛
description: Ph.D, Professor
  Artificial Intelligence and Machine Vision Lab
  Shaanxi University of Science and Technology

  Weiyang University Campus, Xi 'an, Shaanxi Province, China
  （地址：陕西省西安市未央大学园区）

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman